### ISSUE TITLE
The new version of Neovim v0.7.0 is not an snap yet

### ISSUE THREAD

**Issue by Flimm** [neovim/neovim-snap#11]
The latest release of Neovim (v0.7.0) is not yet available on snap. Running `snap install nvim --classic` installs version v0.6.0

**Comment by Flimm** [comment]
I first reported this issue here: https://github.com/neovim/neovim/issues/18289

@clason responded by marking the bug report as invalid, closing it, and locking the issue. He said:

> (As you are by now fully aware of, there's an endorsed repo for a Neovim snap at https://github.com/neovim/neovim-snap, but this is maintained by a community member. Please keep issues regarding snap on that repo.)

I would like to say in good faith that I was not fully aware that an issue like this was only supposed to be reported in the neovim/neovim-snap repo, and not in the neovim/neovim repo. There are many issues in the neovim repo that discuss snap, and the neovim repo also contains many files that relate to snap:

https://github.com/neovim/neovim/tree/master/ci/snap

So it was not clear to me at all that snap issues were not welcome on that repo. I was not doing something that I was "fully aware" was unwelcome. Please accept my apologies for getting it wrong, @clason

**Comment by hurricanehrndz** [comment]
Apologies are not necessary. I am going to be honest though. I don’t think it will happen for several reasons. One, there seems to be little interest in maintaining the snap other than myself. Two, I no longer have the cycles to dedicated time to the snap. Three, the snap itself is causing issues with tree-sitter due to upstream bugs. Four, the team has stalled in how to get the releases automated.

I will circle back with the team and ask about next steps. For now use the edge channel if you wish that is automatically updated with nightly and is very stable.

**Comment by hurricanehrndz** [comment]
I will updated it one more time and the snap is maintained. I will happily fix breaks. I just do not want to be doing manual releases. Which is what is required for anything other than nightlies.

**Comment by hurricanehrndz** [comment]
This was released.

**Comment by hurricanehrndz** [comment]
Yes, the Neovim project does not take responsibility for packaging. It does welcome volunteers and will assist in any way that it can.

I took this on for several reasons that are no longer valid. One, snaps at first seem like a great solution for packaging. Two, I was not comfortable compiling from source. 

The snaps have become more troublesome than I have ever anticipated. The tree sitter issue being the last straw.
