### ISSUE TITLE
Unable to use neovim snap with core22

### ISSUE THREAD

**Issue by rfc2119** [neovim/neovim-snap#14]
I am trying to solve #12 but unfortunately I face the same issue mentioned in #12  with the latest snap. Was the latest snap build with core22 yet ?

**Comment by hurricanehrndz** [comment]
Yes it has been! I will release nightly with core22 soon.

On another note, parsers and other additional libraries will always been an issue that will resurface. This is because a one point or another the version of glibc used within the core snap will not align with the host's version of glibc. This is by design and a feature of snaps. There is very little we can do. I have taken the liberty of including all treesitter parsers in a soon to be publish release. This will not address other additional libraries though such as fzf native.

When you add the dependencies required to compile parsers for treesitter, you practically have all the dependencies required to build neovim from source, so what is the blocker? Parsers for treesitter are built from source, why not build neovim itself from source too?

**Comment by rfc2119** [comment]
Right, glibc version matters and it is indeed a feature of snaps for security and isolation.

Regarding the inclusion of build utilities and libraries in the snap: I didn't know in the first place that snaps may ship with libraries. Out of interest, how will you include them in the snapcraft.yaml file  ? maybe here ?
https://github.com/neovim/neovim-snap/blob/b94e568ecf97d1df870db82d09470853cd49b2e3/snap/snapcraft.yaml#L63-L67

**Comment by hurricanehrndz** [comment]
I think you might have misunderstood, I am not including build utilities. That would cause so many headaches and issues. I am including the parsers, but this will not be the last time the issue occurs. https://github.com/hurricanehrndz/neovim/blob/update_snap_core22/snap/snapcraft.yaml

Because there will be other libraries individuals want, it becomes unmaintainable to compile each and every future possible library.

What I was asking is, is why is the snap your choice of package delivery? Snaps are greater but they are not an ideal solution for personalized dev environments.
